version: '3.9'

services:
  front:
    build:
      context: ./front
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./front:/usr/share/nginx/html
    environment:
      - NODE_ENV=production

  api1:
    build:
      context: ./api
      dockerfile: .docker/Dockerfile
    container_name: api1
    working_dir: /app
    depends_on:
      - database
    expose:
      - "9000"
    networks:
      - src_default
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    build:
      context: ./api
      dockerfile: .docker/Dockerfile
    container_name: api2
    working_dir: /app
    depends_on:
      - database
    expose:
      - "9000"
    networks:
      - src_default
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./front:/usr/share/nginx/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front
      - api1
      - api2
    ports:
      - "80:80"
      - "9999:9999"
    networks:
      - src_default
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  database:
    image: mysql:8.0.40
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: person
    volumes:
      - ./.docker/local/mysql:/var/lib/mysql
    networks:
      - src_default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

networks:
  src_default:
    driver: bridge
