version: '3.5'
services:
  api1: # API - Instância 01
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api1
    working_dir: /var/www/html
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 02
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api2
    working_dir: /var/www/html
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de Dados
    image: mysql:8.0.30
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: teste_pleno
    volumes:
      - ./mysql-data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
